erDiagram
    Sensor {
        UUID id PK "Chave Primária"
        String tipo
        String setor
        String local
        Float limiteMinimo
        Float limiteMaximo
        Timestamp dataCriacao
        Timestamp ultimaAtualizacao
    }
    Leitura {
        UUID id PK "Chave Primária"
        UUID sensorId FK "Chave Estrangeira"
        Float valor
        Timestamp dataMedicao
        Timestamp dataRecebido
    }

    Sensor ||--o{ Leitura : "possui"
